/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HousesImport } from './routes/houses'
import { Route as AuthUserImport } from './routes/_auth-user'
import { Route as AuthOwnerImport } from './routes/_auth-owner'
import { Route as AuthAdminImport } from './routes/_auth-admin'
import { Route as SettingsRouteImport } from './routes/settings/route'
import { Route as ApartmentsRouteImport } from './routes/apartments/route'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsAccountImport } from './routes/settings/account'
import { Route as ApartmentsIdImport } from './routes/apartments/$id'
import { Route as AuthUserProtectedImport } from './routes/_auth-user/protected'
import { Route as AuthOwnerPropertiesImport } from './routes/_auth-owner/properties'
import { Route as AuthAdminAdminImport } from './routes/_auth-admin/admin'
import { Route as AuthOwnerPropertiesAddNewImport } from './routes/_auth-owner/properties_.add-new'

// Create/Update Routes

const HousesRoute = HousesImport.update({
  path: '/houses',
  getParentRoute: () => rootRoute,
} as any)

const AuthUserRoute = AuthUserImport.update({
  id: '/_auth-user',
  getParentRoute: () => rootRoute,
} as any)

const AuthOwnerRoute = AuthOwnerImport.update({
  id: '/_auth-owner',
  getParentRoute: () => rootRoute,
} as any)

const AuthAdminRoute = AuthAdminImport.update({
  id: '/_auth-admin',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRouteRoute = SettingsRouteImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ApartmentsRouteRoute = ApartmentsRouteImport.update({
  path: '/apartments',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsAccountRoute = SettingsAccountImport.update({
  path: '/account',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const ApartmentsIdRoute = ApartmentsIdImport.update({
  path: '/$id',
  getParentRoute: () => ApartmentsRouteRoute,
} as any)

const AuthUserProtectedRoute = AuthUserProtectedImport.update({
  path: '/protected',
  getParentRoute: () => AuthUserRoute,
} as any)

const AuthOwnerPropertiesRoute = AuthOwnerPropertiesImport.update({
  path: '/properties',
  getParentRoute: () => AuthOwnerRoute,
} as any)

const AuthAdminAdminRoute = AuthAdminAdminImport.update({
  path: '/admin',
  getParentRoute: () => AuthAdminRoute,
} as any)

const AuthOwnerPropertiesAddNewRoute = AuthOwnerPropertiesAddNewImport.update({
  path: '/properties/add-new',
  getParentRoute: () => AuthOwnerRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/apartments': {
      preLoaderRoute: typeof ApartmentsRouteImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth-admin': {
      preLoaderRoute: typeof AuthAdminImport
      parentRoute: typeof rootRoute
    }
    '/_auth-owner': {
      preLoaderRoute: typeof AuthOwnerImport
      parentRoute: typeof rootRoute
    }
    '/_auth-user': {
      preLoaderRoute: typeof AuthUserImport
      parentRoute: typeof rootRoute
    }
    '/houses': {
      preLoaderRoute: typeof HousesImport
      parentRoute: typeof rootRoute
    }
    '/_auth-admin/admin': {
      preLoaderRoute: typeof AuthAdminAdminImport
      parentRoute: typeof AuthAdminImport
    }
    '/_auth-owner/properties': {
      preLoaderRoute: typeof AuthOwnerPropertiesImport
      parentRoute: typeof AuthOwnerImport
    }
    '/_auth-user/protected': {
      preLoaderRoute: typeof AuthUserProtectedImport
      parentRoute: typeof AuthUserImport
    }
    '/apartments/$id': {
      preLoaderRoute: typeof ApartmentsIdImport
      parentRoute: typeof ApartmentsRouteImport
    }
    '/settings/account': {
      preLoaderRoute: typeof SettingsAccountImport
      parentRoute: typeof SettingsRouteImport
    }
    '/_auth-owner/properties/add-new': {
      preLoaderRoute: typeof AuthOwnerPropertiesAddNewImport
      parentRoute: typeof AuthOwnerImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ApartmentsRouteRoute.addChildren([ApartmentsIdRoute]),
  SettingsRouteRoute.addChildren([SettingsAccountRoute]),
  AuthAdminRoute.addChildren([AuthAdminAdminRoute]),
  AuthOwnerRoute.addChildren([
    AuthOwnerPropertiesRoute,
    AuthOwnerPropertiesAddNewRoute,
  ]),
  AuthUserRoute.addChildren([AuthUserProtectedRoute]),
  HousesRoute,
])

/* prettier-ignore-end */
